# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('post', models.TextField(max_length=500)),
            ],
        ),
    ]
